FROM python:3.12-alpine3.19

COPY . .

RUN pip3 install -r requirements.txt

ENTRYPOINT ["sh", "./docker-entrypoint-debug.sh"]

#RUN python3 manage.py migrate --settings=config.debug

#CMD [ "python3", "manage.py", "runserver", "0.0.0.0:8000", "--settings=config.debug" ]  
